;;; -*- lexical-binding: t -*-

(require 'test/test-helper)

(ert-deftest dired-indicators-shows-marked-count-and-index ()
  (dired-indicators-test-with-dired-buffer '("alpha" "beta" "gamma")
    (dired-indicators-mode 1)
    (dired-indicators-test-mark-file "alpha")
    (dired-indicators-test-mark-file "gamma")
    (dired-indicators-test-goto-file "gamma")
    (dired-indicators-update)
    (should (equal (substring-no-properties dired-indicators--mode-line-text)
                   " 2/2*"))
    (should (eq (get-text-property 1 'face dired-indicators--mode-line-text)
                'dired-indicators-marked-face))))

(ert-deftest dired-indicators-shows-flagged-count-without-index-away-from-entry ()
  (dired-indicators-test-with-dired-buffer '("alpha" "beta" "gamma")
    (dired-indicators-mode 1)
    (dired-indicators-test-flag-file "beta")
    (dired-indicators-test-flag-file "gamma")
    (dired-indicators-test-goto-file "alpha")
    (dired-indicators-update)
    (should (equal (substring-no-properties dired-indicators--mode-line-text)
                   " 2D"))
    (should (eq (get-text-property 1 'face dired-indicators--mode-line-text)
                'dired-indicators-flagged-face))))

(ert-deftest dired-indicators-combines-marked-and-flagged-segments ()
  (dired-indicators-test-with-dired-buffer '("alpha" "beta" "gamma")
    (dired-indicators-mode 1)
    (dired-indicators-test-mark-file "alpha")
    (dired-indicators-test-mark-file "gamma")
    (dired-indicators-test-flag-file "beta")
    (dired-indicators-test-goto-file "beta")
    (dired-indicators-update)
    (should (equal (substring-no-properties dired-indicators--mode-line-text)
                   " 2* 1/1D"))))

(ert-deftest dired-indicators-respects-customization-toggles ()
  (dired-indicators-test-with-dired-buffer '("alpha" "beta")
    (dired-indicators-mode 1)
    (dired-indicators-test-mark-file "alpha")
    (dired-indicators-test-flag-file "beta")
    (dired-indicators-test-goto-file "beta")
    (let ((dired-indicators-show-marked nil))
      (dired-indicators-update)
      (should (equal (substring-no-properties dired-indicators--mode-line-text)
                     " 1/1D")))
    (let ((dired-indicators-show-flagged nil))
      (dired-indicators-test-goto-file "alpha")
      (dired-indicators-update)
      (should (equal (substring-no-properties dired-indicators--mode-line-text)
                     " 1/1*")))))

(ert-deftest dired-indicators-mode-cleans-up-buffer-local-state ()
  (dired-indicators-test-with-dired-buffer '("alpha")
    (dired-indicators-mode 1)
    (should (memq #'dired-indicators-update post-command-hook))
    (should (memq #'dired-indicators-update dired-after-readin-hook))
    (setq dired-indicators--mode-line-text " 1*")
    (dired-indicators-mode -1)
    (should-not (memq #'dired-indicators-update post-command-hook))
    (should-not (memq #'dired-indicators-update dired-after-readin-hook))
    (should-not dired-indicators--mode-line-text)))

